feat: add connectors UI for Fuel
FuelLabs/fuels-portal pull request #110
Opened 2023-09-12 21:53 UTC by luizstacio

On this PR;
- Add the first work to make a Connect UI that enables the DApp to guide the user to connect with the correct Wallet Connector
- Add a screen to also install the wallet in case the user does not have the wallet yet.

2023-09-15 02:15 UTC, LuizAsFight requested changes
minor things. name pattern for hook and its return, it has been used in sdk-react and also other hooks in this project

2023-09-15 19:49 UTC, luizstacio commented on packages/sdk-react/src/hooks/useConnector.tsx
> +  };
Why someone would need the to know the connector been selected inside the popup? The isOpen I can see it been used.

2023-09-15 19:50 UTC, luizstacio commented on packages/sdk-react/src/ui/Connect/Connect.tsx
> +          <Text fontSize="sm">Connect Wallet</Text>
It was too big in this case because it has the button back and close.

2023-09-15 22:07 UTC, LuizAsFight commented on packages/sdk-react/src/hooks/useConnector.tsx
> +  };
it;s just a matter of repositioning the props to follow pattern / better represent the info.

if it's not needed can remove the connector ?

2023-09-20 15:44 UTC, pedronauck requested changes
Storybook isn't working 😢
![CleanShot 2023-09-20 at 12 44 10@2x](https://github.com/FuelLabs/fuels-portal/assets/2029172/51b8f49f-704a-4178-bb71-88c9176bf886)

2023-09-20 15:46 UTC, pedronauck requested changes
![CleanShot 2023-09-20 at 12 45 42@2x](https://github.com/FuelLabs/fuels-portal/assets/2029172/dcce282e-b732-4362-a5e4-eececd3b242f)

- Overlay title is out of standart, to small
- Logo colors also are not following the brand, should be inverted

2023-09-20 15:48 UTC, pedronauck requested changes
![CleanShot 2023-09-20 at 12 45 50@2x](https://github.com/FuelLabs/fuels-portal/assets/2029172/d08bae58-d16c-47a3-bfd5-843445fc8a36)

- Title too small also
- Logo not in the right colors
- Also I guess the logo is too big on this screen
- Too much margin between "Instal..." and the description text

2023-09-21 02:55 UTC, pedronauck submitted a review, later dismissed

2023-09-21 03:11 UTC, LuizAsFight requested changes

2023-09-21 03:11 UTC, LuizAsFight commented on packages/sdk-react/src/ui/Connect/connectors.ts
> +    link: 'https://next-wallet.fuel.network',
is it possible to send directly to extension link?

`https://chrome.google.com/webstore/detail/fuel-wallet-development/hcgmehahnlbhpilepakbdinkhhaackmc`

2023-09-21 03:17 UTC, LuizAsFight approved these changes

2023-09-21 13:14 UTC, merged