refactor: use new design system header
FuelLabs/fuels-portal pull request #112
Opened 2023-09-19 20:25 UTC by matt-user

closes FRO-545

2023-09-19 20:28 UTC, luizstacio requested changes
Can you implement the mobile one also?

2023-09-20 04:27 UTC, LuizAsFight commented
in the Nav component we can also include the `network` , `account` and `onConnect` props to make it like this one ?
https://design.fuel.network/?path=/story/ui-nav--usage

@luizstacio ok ?

2023-09-20 13:45 UTC, luizstacio commented
> in the Nav component we can also include the `network` , `account` and `onConnect` props to make it like this one ? https://design.fuel.network/?path=/story/ui-nav--usage
> 
> @luizstacio ok ?

We can open an issue to prioritize this in the next cycle.

2023-09-20 15:29 UTC, luizstacio requested changes

2023-09-20 15:29 UTC, luizstacio commented on packages/app/src/systems/Core/components/Header.tsx
> +        </Nav.Menu>
We need to keep the logic that uses the `IS_PREVIEW`; They ensure that when we are on the ecosystem page, the menu items are not shown.

2023-09-27 20:37 UTC, luizstacio requested changes
Can you take a look why page refreshes on each click, it should just change the route using react router.

2023-09-28 16:10 UTC, luizstacio approved these changes

2023-09-28 16:10 UTC, merged