feat: network connect card
FuelLabs/fuels-portal pull request #15
Opened 2023-04-17 22:19 UTC by matt-user

2023-04-18 15:47 UTC, luizstacio requested changes
The component looks bigger than the design specs, I think we need to change some scale down.

2023-04-18 15:47 UTC, luizstacio commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.stories.tsx
> +        networkImageUrl="public/fuel-logo.svg"
The logo of Fuel does not appear in the storybook. You can import the image using `import imageSrc from '../../public/fuel-logo.svg'`.

2023-04-18 16:40 UTC, LuizAsFight requested changes
change request in previous comment. I didn't check the code yet, only visual aspect

2023-04-19 01:16 UTC, luizstacio requested changes
Just some change, is looking great

2023-04-19 01:16 UTC, luizstacio commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.stories.tsx
> +        heading="To"
```suggestion
        label="To"
```

2023-04-19 01:16 UTC, luizstacio commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +            )}
In order to align the center button and network, we need to change the structure here to something like this;
```suggestion
          </Stack>
          <Flex align="space-between" justify="center">
             <Flex gap="$2" align="center">
              <Image width="20" height="20" src={networkImageUrl} />
              <Text color="blackA12">{networkName}</Text>
            </Flex>
            <Box>
            {!currentAccount ? (
              <Button
                onPress={onConnect}
                isLoading={isConnecting}
                css={styles.buttonRoot}
              >
                Connect wallet
              </Button>
            ) : (
              <Button
                onPress={onConnect}
                isLoading={isConnecting}
                leftIcon={<Icon icon="Circle" color="red10" fill="red10" />}
                rightIcon="CaretDown"
                variant="outlined"
                css={{ ...styles.buttonRoot, ...styles.accountButton }}
              >
                {formatAddress(currentAccount)}
              </Button>
            )}
            <Box>
          </Flex>
```

2023-04-19 23:40 UTC, LuizAsFight commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +  isConnecting: boolean;
isConnecting can be optional

2023-04-19 23:47 UTC, LuizAsFight commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +  buttonRoot: cssObj({
can we change to `connectButton` ?

2023-04-19 23:48 UTC, LuizAsFight commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +  }),
styling not needed

2023-04-20 19:03 UTC, LuizAsFight requested changes

2023-04-20 19:03 UTC, LuizAsFight commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +  accounts?: `0x${string}`[] | Bech32Address[];
I think this is a leftover

2023-04-20 19:03 UTC, LuizAsFight commented on packages/app/src/systems/Bridge/components/NetworkConnectCard/NetworkConnectCard.tsx
> +  currentAccount?: `0x${string}` | Bech32Address;
can we change to `string`? otherwise it will make you need to do some typeguard before passing to this currentAccount component

2023-04-20 19:26 UTC, LuizAsFight approved these changes

2023-04-20 19:31 UTC, luizstacio approved these changes

2023-04-20 19:49 UTC, merged