docs: Ecosystem Page V2
FuelLabs/fuels-portal pull request #204
Opened 2023-12-08 15:24 UTC by Rubyt0x

New features:
- **Featured Projects:** a carousel featuring projects live on Testnet based on their categories.
- **Project Details side panel:** opens a side panel with more information about each project on a card click.
- **Informative Alert:** An alert tells people to click on cards.

Design enhancements:
- Card design enhancement: improved layout, social buttons

Fixes #197

2024-01-10 13:31 UTC, luizstacio requested changes
@Rubyt0x: 
1. can you add a cursor pointer when use hovers the card?
2. None of the buttons work... the only one that works is visit website with the project tab open. 
<img width="509" alt="Screenshot 2024-01-10 at 10 44 36" src="https://github.com/FuelLabs/fuels-portal/assets/3941923/3fde600a-4905-4950-87ee-b5e4ccec7b71">
<img width="1044" alt="Screenshot 2024-01-10 at 10 44 56" src="https://github.com/FuelLabs/fuels-portal/assets/3941923/fdc510bd-9c28-4cd4-9283-0489cbcb60ac">
3. I think would be better to add the Visit Website button near to the logo, right now is easy to not see it.
<img width="1015" alt="Screenshot 2024-01-10 at 10 32 12" src="https://github.com/FuelLabs/fuels-portal/assets/3941923/3e200bc0-130f-48d8-981b-edaf4ef9b0e8">

2024-01-10 13:40 UTC, luizstacio requested changes
- Can you remove the inline styles, move them to the styles cost we have always creating a new item for it. Ex from `style={{ a: 1 }} to style={styles.myA}`
- You could also split more the code, and improve the use of state, but we can do this later.

2024-01-10 13:40 UTC, luizstacio commented on packages/app/src/systems/Ecosystem/components/FeaturedProjects/FeaturedProjects.tsx
> +      </style>
This should be in a css file.

2024-01-11 06:42 UTC, LuizAsFight requested changes
social buttons are grabbing too much attention, maybe try to do only bordered instead of background?

or keep same color? specially the X one when it's alone, that red button is the first thing you look

2024-01-12 11:22 UTC, Rubyt0x commented on packages/app/src/systems/Ecosystem/components/FeaturedProjects/FeaturedProjects.tsx
> +      </style>
Moved to animations.css

2024-01-22 19:38 UTC, LuizAsFight commented
yes @Rubyt0x much better now, I will fix audit in other PR then you can get rid of CI error

2024-01-23 01:13 UTC, LuizAsFight approved these changes

2024-01-23 16:39 UTC, LuizAsFight requested changes
other changes requested from product side will come, so I'm blocking it for now

2024-02-22 00:47 UTC, closed without merging