feat: fuel account connection
FuelLabs/fuels-portal pull request #35
Opened 2023-04-26 19:56 UTC by matt-user

closes FRO-6

2023-04-28 19:01 UTC, matt-user commented
making this pr a draft until https://github.com/FuelLabs/fuels-wallet/pull/726 is merged and I can use the fix

2023-05-05 17:41 UTC, LuizAsFight requested changes
1- let's include new hooks that will be needed really soon:
`useIsConnected`
`useProvider`

2- let's make all hooks have the same output pattern:
consider that `queryProps` is the output of both `useMutation`/`useQuery`. like onLoading, isIdle, etc...

output of hooks will be:
`{ data, handlers, ...queryProps }`

for example `useAccount`
```
return {
  data: address,
  ...queryProps
}
```


for example useConnect
```
return {
  data,
  handlers: {
    connect
  },
  ...queryProps
}
```


on this way we know that for every hook `data` will be inside data props. actions will be inside `handlers` prop, and all other props are related to query status/loading/errors/etc

2023-05-05 17:41 UTC, LuizAsFight commented on packages/hooks/src/hooks/useAccount.tsx
> +      }
let's not use `null`. also this code can be smaller

```suggestion
      try {
        const currentFuelAccount = await fuel?.currentAccount();
        return currentFuelAccount;
      } catch (e) {
        return undefined;
      }
```

2023-05-05 17:41 UTC, LuizAsFight commented on packages/hooks/src/hooks/useConnect.tsx
> +    data,
can we remove the comments?

```suggestion
  return {
    connect: mutate,
    data,
```

2023-05-05 17:41 UTC, LuizAsFight commented on packages/app/src/systems/Accounts/hooks/useAccountConnectionFuel.tsx
> +    fuel,
we should not return `fuel`, could return something like:
`hasInstalledFuel: Boolean(fuel)`

2023-05-05 17:41 UTC, LuizAsFight commented on packages/hooks/src/hooks/useAccount.tsx
> +    isConnected: !!data,
I think this line is a problem as we can have different results from `fuel.isConnected` function. `useAccount` hook should only return `address`.. let's keep `isConnected` to other hook

2023-05-08 23:58 UTC, matt-user commented on packages/app/src/systems/Accounts/components/FuelInstallPopup/FuelInstallPopup.tsx
> +    color: 'Black',
yes, but this pr does not have the new fuel-ui version.  That pr is what I will work on next and will fix this issue.

2023-05-09 23:32 UTC, LuizAsFight requested changes

2023-05-09 23:32 UTC, LuizAsFight commented on packages/app/src/systems/Accounts/pages/AccountConnectionFuel.tsx
> +  const nonNullAddress = !account ? undefined : account!;
this line is not needed anymore

2023-05-09 23:47 UTC, LuizAsFight requested changes

2023-05-09 23:47 UTC, LuizAsFight commented on packages/sdk-react/src/hooks/useAccount.tsx
> +    }
```suggestion
      try {
        const currentFuelAccount = await fuel?.currentAccount();
        return currentFuelAccount || null;
      } catch (error: unknown) {
        return null;
      }
    }
```

2023-05-09 23:47 UTC, LuizAsFight commented on packages/sdk-react/src/hooks/useIsConnected.tsx
> +    return isConnected;
```suggestion
    return isConnected || false;
```

2023-05-09 23:47 UTC, LuizAsFight commented on packages/sdk-react/src/hooks/useIsConnected.tsx
> +    isConnected: data || undefined,
```suggestion
    isConnected: data,
```

2023-05-09 23:47 UTC, LuizAsFight commented on packages/sdk-react/src/hooks/useProvider.tsx
> +    return provider;
```suggestion
    const provider = await fuel?.getProvider();
    return provider || null;
```

2023-05-10 15:43 UTC, LuizAsFight approved these changes
as @matt-user will be OOO for some days I will approve this PR as-is and implement remaining (minor) requested changes in this PR #38

2023-05-10 15:43 UTC, merged