test: e2e test
FuelLabs/fuels-portal pull request #51
Opened 2023-06-14 21:06 UTC by matt-user

closes FRO-141

2023-06-30 15:00 UTC, LuizAsFight commented on packages/app/playwright/e2e/Bridge.test.ts
> +    ).toBe('1');
can we use `bn` to do this type of checking ?

2023-06-30 15:06 UTC, LuizAsFight commented on packages/app/playwright/e2e/Bridge.test.ts
> +    });
```suggestion
    const preWithdrawBalanceFuel = await fuelWallet.getBalance(NativeAssetId);
    const preWithdrawBalanceEth = await client.getBalance({
      address: account.address,
    });
```

2023-06-30 15:13 UTC, LuizAsFight requested changes

2023-06-30 15:13 UTC, LuizAsFight commented on packages/app/playwright/e2e/fixtures.ts
> +            console.log('Download Completed extracting zip...');
skip comment  lint for this file

2023-06-30 15:13 UTC, LuizAsFight commented on packages/app/playwright/e2e/fixtures.ts
> +    });
can we put this key/password in a mock file to reuse if need?

2023-06-30 15:13 UTC, LuizAsFight commented on packages/app/src/systems/Chains/eth/containers/TxEthToFuelDialog.tsx
> +          <Dialog.Close aria-label="Close unlock window" />
```suggestion
          <Dialog.Close aria-label="Close Transaction Dialog" />
```

2023-06-30 15:13 UTC, LuizAsFight commented on packages/app/src/systems/Chains/fuel/containers/TxFuelToEthDialog.tsx
> +          <Dialog.Close aria-label="Close unlock window" />
```suggestion
          <Dialog.Close aria-label="Close Transaction Dialog" />
```

2023-07-05 16:02 UTC, matt-user commented on packages/app/playwright/commons/wallet.ts
> +  await signupPage.waitForTimeout(9000);
I wasn't able to get the tests to work with `waitForTimeout` :/

2023-07-05 19:53 UTC, matt-user commented
> would be also nice to check steps component progression during the test. checking if icon done appeared, if correct step is selected, etc

I'm not sure if it is possible to check if the icon changes.  All I think we can check is if the text changes.

2023-07-26 23:51 UTC, LuizAsFight requested changes
when running locally it fails here : 

![image](https://github.com/FuelLabs/fuels-portal/assets/8636507/0a7d9f5c-ea87-4828-9626-fa8f22989ad3)

in the second transaction of metamask (withdraw), gets locked here \/, test would need to click in "I want to proceed anyway"
![image](https://github.com/FuelLabs/fuels-portal/assets/8636507/7c043927-b8a3-40d7-ad55-0fa5ec903f11)

2023-08-01 22:00 UTC, LuizAsFight approved these changes
congratz on this work @matt-user

2023-08-01 22:00 UTC, LuizAsFight commented on package.json
> +    "test:all": "run-s test test:e2e",
can we do `run-p` ?

2023-08-01 22:00 UTC, merged