feat: update fuel-core + wallet + ts-sdk
FuelLabs/fuels-portal pull request #70
Opened 2023-07-26 15:56 UTC by LuizAsFight

2023-08-28 21:14 UTC, LuizAsFight commented on docker/fuel-core/Dockerfile
> +ARG FUEL_PORT=4001
using same pattern of [fuel-bridge](https://github.com/FuelLabs/fuel-bridge) repo

4001 is only internally, it is still exposed on localhost:4000

2023-08-28 21:16 UTC, LuizAsFight commented on packages/app/src/systems/Chains/fuel/hooks/useTxFuelToEth.tsx
> +    if (txId && !skipAnalyzeTx && fuelProvider) {
yes, thanks

2023-08-29 03:49 UTC, luizstacio requested changes
- After starting a deposit, when going to the transactions page, it throws an error `Cannot read properties of null (reading 'header')`,

2023-08-29 14:56 UTC, luizstacio approved these changes

2023-08-29 14:56 UTC, merged