feat: notification l1 listener
FuelLabs/fuels-portal pull request #92
Opened 2023-08-14 22:59 UTC by matt-user

2023-09-25 20:37 UTC, luizstacio requested changes

2023-09-25 20:37 UTC, luizstacio commented on packages/notification-service/src/utils/handleNewEthBlock.ts
> +              from: 'matt.auer@fuel.sh',
We should make from a env configuration.

2023-09-25 20:37 UTC, luizstacio commented on packages/notification-service/src/services/mailService.ts
> +      from: `"Fred Foo" ${options.from}`,
We should make from a env configuration.

2023-09-25 20:37 UTC, luizstacio commented on packages/notification-service/src/services/mailService.ts
> +      },
All this configures should be received using. env variables

2023-09-27 14:50 UTC, luizstacio requested changes

2023-09-27 14:50 UTC, luizstacio commented on package.json
> +      "undici@>=2.0.0 <5.19.1": ">=5.19.1"
Do we need this things here?

2023-09-27 14:50 UTC, luizstacio commented on packages/notification-service/package.json
> +    "wagmi": "^1.0.6"
I think we can remove `wagmi` as this project only uses backend `viem`

2023-09-27 14:50 UTC, luizstacio commented on packages/notification-service/package.json
> +    "graphql-tag": "^2.12.6",
I think we can remove this deps also

2023-09-27 14:50 UTC, luizstacio commented on packages/notification-service/src/index.ts
> +      ),
On the docs it says that transport is just `transport: http()` why we need to grap config again here as it cames from the load.env.js?

2023-09-27 14:50 UTC, luizstacio commented on packages/notification-service/src/index.ts
> +  isDev ? process.env.FUEL_PROVIDER_URL! : 'https://beta-4.fuel.network/graphql'
As this is loaded on the `load.env.js` I think we don't need a default value.

2023-09-27 14:57 UTC, matt-user commented on package.json
> +      "undici@>=2.0.0 <5.19.1": ">=5.19.1"
yes, without them the audit fails.

2023-09-27 17:19 UTC, luizstacio approved these changes

2023-09-27 17:19 UTC, merged